# This is a **reuseable** workflow that builds the CLI for Apple Silicon macOS.
# It doesn't get triggered on its own. It gets used in:
#  - release.yml
#  - canary.yml
on:
  workflow_call:
    inputs:
      version:
        required: false
        default: ""
        type: string
      ref:
        type: string
        required: false
        default: ""

name: "Reusable workflow to build CLI"

jobs:
  build-cli:
    name: Build CLI
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: "12.0"
      TARGET: aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: ${{ inputs.ref }}

      - name: Update version in Cargo.toml
        if: ${{ inputs.version != '' }}
        shell: bash
        run: |
          sed -i.bak 's/^version = ".*"/version = "'${{ inputs.version }}'"/' Cargo.toml
          rm -f Cargo.toml.bak

      - name: Cache Cargo artifacts
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1
        with:
          key: aarch64-apple-darwin-macos-latest-macos-deployment-target-12

      - name: Build CLI
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1
        run: |
          source ./bin/activate-hermit
          rustup target add "${TARGET}"
          echo "Building for target: ${TARGET}"
          rustup show
          cargo build --release --target ${TARGET} -p goose-cli

      - name: Package CLI
        run: |
          source ./bin/activate-hermit
          mkdir -p "target/${TARGET}/release/goose-package"
          cp "target/${TARGET}/release/goose" "target/${TARGET}/release/goose-package/"
          cd "target/${TARGET}/release"
          tar -cjf "goose-${TARGET}.tar.bz2" -C goose-package .
          tar -czf "goose-${TARGET}.tar.gz" -C goose-package .
          echo "ARTIFACT_BZ2=target/${TARGET}/release/goose-${TARGET}.tar.bz2" >> $GITHUB_ENV
          echo "ARTIFACT_GZ=target/${TARGET}/release/goose-${TARGET}.tar.gz" >> $GITHUB_ENV

      - name: Upload CLI artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a  # v7.0.1
        with:
          name: goose-aarch64-apple-darwin
          path: |
            ${{ env.ARTIFACT_BZ2 }}
            ${{ env.ARTIFACT_GZ }}
